sudo: false
language: node_js
node_js:
    - '10'
branches:
    only:
        - master
        - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
cache:
    directories:
        - node_modules
before_install:
    - npm update
install:
    - npm install
script:
    - npm test
    - npm run coveralls
